### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/float32-signbit#1]
Dependent on math-io/float32-to-word#1.

**Comment by Planeshifter** [comment]
Looks good. With respect to all `float32-` modules, I am wondering whether a notice in the `README.md` file might be in order, which justifies and explains their existence. Given that JS does not allow us (yet) to define numbers of type `float32`, this might be called for. What do you think?

**Comment by kgryte** [comment]
JS does allow `float32`. :) This is the purpose of [`Math.fround`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround). `Math.fround` was [introduced](https://blog.mozilla.org/javascript/2013/11/07/efficient-float32-arithmetic-in-javascript/) to achieve something similar to a type annotation for use by Emscripten. Granted, `float32` values are not easily accessible in userland atm, but should become more available with `typed-objects`. While a compiler may return a `float32` value when accessing a `Float32Array` element, things are made ambiguous by the fact that anything and everything is promoted to `Float64`.

So yes, these modules are pre-emptive, but probably not as far off as most think.

Thanks for reviewing!
